const {
  generateRegistrationOptions,
  verifyRegistrationResponse,
  generateAuthenticationOptions,
  verifyAuthenticationResponse,
} = require('@simplewebauthn/server');

/**
 * SimpleWebAuthnService — infrastructure adapter wrapping the
 * @simplewebauthn/server library. This is the ONLY file in the codebase
 * that talks to the WebAuthn library directly; use cases depend on this
 * through duck-typing (constructor injection), so the library could be
 * swapped without touching application/domain code.
 */
class SimpleWebAuthnService {
  /**
   * @param {object} params
   * @param {string} params.rpName - Human-friendly relying party name
   * @param {string} params.rpID - Relying party domain (no scheme/port)
   * @param {string} params.origin - Exact origin(s) the frontend is served from
   */
  constructor({ rpName, rpID, origin }) {
    this.rpName = rpName;
    this.rpID = rpID;
    this.origin = origin;
  }

  /**
   * @param {object} params
   * @param {import('../../domain/entities/User')} params.user
   * @param {import('../../domain/entities/Credential')[]} params.excludeCredentials
   */
  async generateRegistrationOptions({ user, excludeCredentials = [] }) {
    return generateRegistrationOptions({
      rpName: this.rpName,
      rpID: this.rpID,
      userName: user.username,
      userDisplayName: user.displayName,
      // userID is auto-generated by the library when omitted; we key
      // everything in our own storage by our own User.id instead.
      attestationType: 'none',
      excludeCredentials: excludeCredentials.map((cred) => ({
        id: cred.id,
        transports: cred.transports,
      })),
      authenticatorSelection: {
        residentKey: 'preferred',
        userVerification: 'preferred',
      },
    });
  }

  /**
   * @param {object} params
   * @param {object} params.response - RegistrationResponseJSON
   * @param {string} params.expectedChallenge
   */
  async verifyRegistrationResponse({ response, expectedChallenge }) {
    return verifyRegistrationResponse({
      response,
      expectedChallenge,
      expectedOrigin: this.origin,
      expectedRPID: this.rpID,
    });
  }

  /**
   * @param {object} params
   * @param {import('../../domain/entities/Credential')[]} params.allowCredentials
   */
  async generateAuthenticationOptions({ allowCredentials = [] }) {
    return generateAuthenticationOptions({
      rpID: this.rpID,
      userVerification: 'preferred',
      allowCredentials: allowCredentials.map((cred) => ({
        id: cred.id,
        transports: cred.transports,
      })),
    });
  }

  /**
   * @param {object} params
   * @param {object} params.response - AuthenticationResponseJSON
   * @param {string} params.expectedChallenge
   * @param {import('../../domain/entities/Credential')} params.credential
   */
  async verifyAuthenticationResponse({ response, expectedChallenge, credential }) {
    return verifyAuthenticationResponse({
      response,
      expectedChallenge,
      expectedOrigin: this.origin,
      expectedRPID: this.rpID,
      credential: {
        id: credential.id,
        publicKey: credential.publicKey,
        counter: credential.counter,
        transports: credential.transports,
      },
    });
  }
}

module.exports = SimpleWebAuthnService;
